version: 2.1

orbs:
  maven: circleci/maven@1.1
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@02.1.0

executors:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies for project
          command: mvn package

workflows:
  test_build_and_deploy:
    jobs:
      - maven/test:
          executor: jdk8
      - build:
          requires:
            - maven/test